---
title: "Final Project"
subtitle: "Project Proposal"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
self-contained: true
---

## Project Proposal - Data

### Reading in Data

```{r}
library(tidyverse)
library(here)

child_mortality <- read.csv("child_mortality_0_5_year_olds_dying_per_1000_born.csv")
GDP_per_Cap <- read.csv("gdp_pcap.csv")
```

### Data at a Glance

```{r}
head(child_mortality)
head(GDP_per_Cap)


# mortality NAs 
sum(is.na(child_mortality))

# GDP NAs
sum(is.na(GDP_per_Cap))
```

### 1 Let's Start Cleaning

#### 1.1 Limit Range
-   Some countries did not exist until 1950 (assumed they get their independence from a colonial power this year, so refine data frames to remove cols X1800 - X 1949

```{r}
# Refine child_mortality dataset
child_mortality <- child_mortality |>
  select(country, `X1950`:`X2100`)

# Refine GDP_per_Capita dataset
GDP_per_Cap <- GDP_per_Cap |>
  select(country, `X1950`:`X2100`)

#Renaming cols
child_mortality <- child_mortality|>
  rename_with(~ str_replace(., "^X", ""), .cols = everything())

GDP_per_Cap <- GDP_per_Cap |>
  rename_with(~ str_replace(., "^X", ""), .cols = everything())

```

#### 1.2 Pivoting Longer

```{r}
child_mortality_long <- child_mortality |>
  pivot_longer(
    cols = !country,
    names_to = "Year",
    values_to = "Mortality Rate"
  )

GDP_per_Cap_long <- GDP_per_Cap |>
  pivot_longer(
    cols = !country,
    names_to = "Year",
    values_to = "GDP Per Capita"
  )

```

#### 1.3 Convert to Numeric 
```{r}
# function converts numbers in "XXk" format to numeric
# eg "89k" -> 89,000
convert_k_to_number <- function(x) {
  if (grepl("k", x, fixed = TRUE)) {
    numeric_value <- as.numeric(sub("k", "", x)) * 1000
  } else {
    numeric_value <- as.numeric(x)
  }
  return(numeric_value)
}
```

```{r}
# converts mortality rate to numeric
child_mortality_long <- child_mortality_long |>
  filter(!is.na(child_mortality_long$`Mortality Rate`)) |>
  mutate(`Mortality Rate` = as.numeric(`Mortality Rate`))

# converts gdp to numeric
GDP_per_Cap_long <- GDP_per_Cap_long |>
  mutate(`GDP Per Capita` = map(`GDP Per Capita`, convert_k_to_number))
```

#### 1.4 Joining Datasets
```{r}
joined_df <- inner_join(child_mortality_long, GDP_per_Cap_long, join_by(country, Year))

joined_df
```

